CREATE USER 
'saasia'@'localhost' 
IDENTIFIED  BY 'SaasIA123$';

GRANT USAGE ON *.* TO 'saasia'@'localhost';

ALTER USER 'saasia'@'localhost' 
REQUIRE NONE 
WITH MAX_QUERIES_PER_HOUR 0 
MAX_CONNECTIONS_PER_HOUR 0 
MAX_UPDATES_PER_HOUR 0 
MAX_USER_CONNECTIONS 0;

GRANT ALL PRIVILEGES ON saasia.* 
TO 'saasia'@'localhost';

FLUSH PRIVILEGES;

EXIT;